@baseUrl = http://localhost:8080/usuarios

### GET todos los usuarios
GET {{baseUrl}}


### GET usuario por ID
GET {{baseUrl}}/1


### POST crear usuario
POST {{baseUrl}}
Content-Type: application/json

{
    "nombre": "Tais",
    "apellido": "Orellana",
    "fechaNacimiento": "2000-05-14",
    "direccion": "Santiago, Chile",
    "correoElectronico": "tais.orellana@email.com"
}

### DELETE eliminar usuario por ID
DELETE {{baseUrl}}/1